--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AxelFeL/ChatToDiscord
build-by-default: true
branches:
- main
projects:
  ChatToDiscord:
    path: ""
    libs:
      - src: CortexPE/DiscordWebhookAPI
        version: ^1.0.2
       
...
